### PR TITLE
Finish xlocale removal, fix CPP declarations, other tidy-ups

### LINKED ISSUE #53: To CPP or not to CPP...
On MacOS, defining the C preprocessor to be  `cpp` appears to be a sub-optimal choice. When invoked this way it runs with `-traditional-cpp`. One feature of that, apparently, is that the format of pre-processor directives is somewhat constrained. For example, no indentation. 

I see an unwelcome result of this when compiling libpng:

```
In file included from /usr/include/Availability.h:190:
/usr/include/AvailabilityInternal.h:22938:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_12
         ^
/usr/include/AvailabilityInternal.h:22867:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_4
         ^
... about 25 similar lines snipped ...

/usr/include/AvailabilityInternal.h:30:2: error: unterminated conditional directive
#ifndef __AVAILABILITY_INTERNAL__
 ^
In file included from ./png.h:397:
In file included from /usr/include/zlib.h:34:
In file included from /usr/include/zconf.h:439:
In file included from /usr/include/unistd.h:72:
In file included from /usr/include/sys/unistd.h:182:
/usr/include/Availability.h:239:2: error: #else without #if
#else
 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
Despite the errors, the compilation of libpng does complete.

I observe that the variables `$GCC`, `$GPP`, and `$GXX`, and their use in various `./configure` stanzas, were introduced into the `buildme.sh` script as a by-product of this commit: _Upgrade ICU to 58.2, necessary collation and build patches._  https://github.com/Logitech/slimserver-vendor/commit/cb7e0ad0e28d685c1a699f5aad9e92bfb1347807

I think they were introduced to support some differing FreeBSD build environments.

On MacOS, it seems that either `cc -E` or `gcc -E` are appropriate ways of invoking the preprocessor. I suspect that, left to their own devices,  the various configure scripts would work this out for themselves. And, possibly, the c-compiler and c++-compiler too ?

So, I think something should be changed, but I'm not clear what.  Could @fsbruva comment ?

### LINKED ISSUE #57: xlocale.h patch causes problem in Freenas 11.1
When installing on FreeNAS 11.1, I had to comment out the following line since it was not able to find the strtod_l. I believe that function is defined in this xlocale.h. Commenting out the patch fixed my problem.
# Need to patch ICU to adapt to removal of xlocale.h on some platforms.
#patch -p0 < ../../icu58_patches/digitlst.cpp.patch

Also, I was unable to use perl5.26. I only got stuff working with perl5.24.1

### PR DESCRIPTION
**Pull request by fsbruva**
This is a proposed set of 8 commits, to address reported issues, and revert recent changes that break the build for old Perls.

1. Fix ICU build on FreeBSD 11.1
The FreeBSD automake doesn't notice/care that the automake.ac file was changed by the previous patch. Fixes #57 .

2. Remove erroneous CC/CXX/CPP declaration
The previous addition of the explicit CPP declaration caused problems on MacOS, so this commit addresses that. Fixes #53 .

3. Detect CC/CXX defined in environment
Add code to use the $CC and $CXX variables in the environment or commandline.

4. Skip tests to enable Data-Dump build with old Perl
The Data::Dump module tests fail in FreeBSD jails and Perl 5.10 and below. 

5. Add trailing slash to enable build.
The 'find' operation to detect the zlib headers fails on old FreeBSD without trailing slash.

6. Skip DBI tests for really old Perl
The re-enabling of tests for DBI in b3e127b introduced a regression, where the build failed with Perl 5.8. 

7. Disable asm for certain gcc, clean FreeBSD arch detect
There are known issues with compiling ffmpeg with gcc 4.2, especially with asm optimizations on amd64 FreeBSD platforms. Disable all asm, and make FreeBSD arch tests more robust.

8. This PR also includes a minor fix to comments describing the CC detection scheme for FreeBSD.
 
This set of commits builds successfully on:

- Centos 7 x86_64 (Perl 5.16.3, gcc 4.8.5)
- Debian 9.5 amd64 (Perl 5.24.1, gcc 6.3.0)
- Debian 9.5 i386 (Perl 5.24.1, gcc 6.3.0)
- Ubuntu 18.04.1 x86_64 (Perl 5.26.1, gcc 7.3.0)
- FreeBSD 11.2 amd64 (5.26.2 & 5.28.0, clang 6.0.0)
- FreeBSD 11.1 amd64 (Perl 5.22.4 & 5.24.4 & 5.26.1, clang 4.0.0)
- FreeBSD 7.2 amd64 (Perl 5.8.9 & 5.10.1 & 5.12.4, gcc 4.2.1)
- FreeBSD 7.2 i386 (Perl 5.8.9 & 5.10.1 & 5.12.4, gcc 4.2.1)

### CODE REVIEW

**Comment by mherger** [comment]
Is FreeBSD 7.x with Perl 5.8 still relevant? Is there added complexity for this ancient platform which complicates things?

**Comment by fsbruva** [comment]
No, FreeBSD 7.2 is not relevant. However, it's quickest way I found to install Perl 5.8 for testing. The added complexities from using this version of FreeBSD are:
1. `find` can't tolerate a missing trailing '/'
2. It ships with gcc 4.2.1 as the stock compiler, which has always had problems with ffmpeg's asm optimizations (regardless of platform). This version of gcc was stock all the way through FreeBSD 9.x.

The added complexities from using Perl 5.8 are:
1. Can't run the tests for DBI (my bugfix corrects a regression - these tests were always disabled before)
2. Can't run tests for Data-Dump in a jail (like a GNU/Linux chroot)

There is no pride in authorship. Please let me know how you'd like to proceed.

**Comment by fsbruva** [comment]
@mherger - Are you still reviewing the changes in this PR? Would you prefer I rebase and drop the commits that correspond to 4, 5 and 6 in the PR summary?

**Comment by mherger** [comment]
I do review the changes. But I obviously failed in the past. And I currently don't have the bandwidth to extensively test this. Therefore I hoped one of the reporters would have chimed in.

**Comment by mherger** [comment]
That certainly fixed my build issues on macOS. Thanks!

**Comment by fsbruva** [comment]
@mherger Believe me - I completely understand. I set out to fix those first two reported issues at the beginning of the summer. `blink(); blink();` Now it's September. Glad the macOS build worked.
